name: C++ Build on Linux

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:    

    - name: Checkout project and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install Google Test
      run: sudo apt install libgtest-dev

    - name: Install ALSA
      run: sudo apt-get install libasound2-dev

    - name: Install SNDFile
      run: |
        sudo apt-get install libsndfile1
        sudo apt-get install libsndfile1-dev
      
    - name: Install GPS
      run: |
        sudo apt-get install gpsd gpsd-clients libgps-dev
        
    - name: Generate
      run: cmake -B build

    - name: Build
      run: make -C build
