name: C++ Build on Linux

on: [push]

env:
  BUILD_NAME: Processing_Server
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:    

    - name: Checkout project and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
     
    - name: Generate
      run: cmake -B build -S Processing_Server

    - name: Build
      run: make -C build