# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ReleaseMSBuild

on:
  release:
    types: [published]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: PL_Windows_Proc_Serv.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Debug

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable long file paths
      run: git config --system core.longpaths true

    - name: Checkout project and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /m:1 # /m:1 set to one parallel build

    - uses: actions/checkout@master
    - name: Copy Config and README
      run: |
        cp "PL_Windows_Proc_Serv/Config.json" "/build/Config.json"
        cp "README.md" "/build/README.md"

    - name: Zip Docs and Build
      uses: TheDoctor0/zip-release@0.7.6
      with:
       path: /build/* # File to add to the archive
       Filename: PL_Windows_Proc_Serv.zip # The name of the archive file

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          PL_Windows_Proc_Serv.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



      
